### ISSUE TITLE
Passed Local Tests! . . . but I Haven't

### ISSUE THREAD

**Issue by gasganno** [learn-co-curriculum/javascript-fix-the-scope-lab#23]
The Learn IDE is suddenly saying that 0 tests have passed when I've actually solved 5 of them. But the lesson page in Chrome is saying I passed the local tests. This happens periodically. I'm stuck on a lesson in the Swift course that I definitely haven't solved but the Lesson page light has turned to green.

![screen shot 2017-09-18 at 7 30 33 pm](https://user-images.githubusercontent.com/26098882/30569270-de5a50da-9ca7-11e7-8895-12a6c4bca84d.png)

<img width="1559" alt="screen shot 2017-09-18 at 7 30 55 pm" src="https://user-images.githubusercontent.com/26098882/30569274-ea95785c-9ca7-11e7-93e4-46261a4c9481.png">

**Comment by maxwellbenton** [comment]
Hi @gasganno,

Thank you for spotting this and providing feedback. This error was due to an issue in the dependencies of this lesson. We've updated the `package.json` file and confirmed that this issue is now resolved.

We apologize for any frustration this may have caused, but we appreciate you taking the time to provide this feedback.
